### PR TITLE
Adds Preact support

### PR DESCRIPTION
**Pull request by alistair-king**
Adds Preact support by cloning MsalReactTester.ts to MsalPreactTester.ts and changing the import of waitFor to the preact version.

### CODE REVIEW

**Comment by Mimetis** [comment]
Thanks for your contribution @alistair-king !

I think that making a copy - paste of the main class `MsalReactTester` is not a good thing, to be honest.
- Will be very complicated to maintain at least, if something is changing.
- A lot of duplicate code
- A package added that will never be used with react application

that being said, I think there is a solution to be more elegant, and still adding the preact support.

If you look the `MsalReactTesterPlugin` class, we have a `ITestRunner` interface implemented by default, that you can implement in your own project

It's mainly here, because with a `Vite.js` project, we don't have `jest`:

``` ts
    public static TestRunner: ITestRunner = {
        spyOn: typeof jest !== 'undefined' ? jest.spyOn : () => { },
        expect: typeof jest !== 'undefined' ?  expect : () => { },
        resetAllMocks: typeof jest !== 'undefined' ? jest.resetAllMocks : () => { }
    };
```

As an example, the `Vite `sample is implementing its own `ITestRunner` as it does not support `Jest`.
We are just implementing the interface with the `vitest` functions (instead of `jest`)

https://github.com/Mimetis/msal-react-tester/blob/main/vite-sample/src/test.config.ts :

``` ts
import { vi, expect } from 'vitest'

MsalReactTesterPlugin.init({
  spyOn: vi.spyOn,
  expect: expect,
  resetAllMocks: vi.resetAllMocks
})
```

Now imagine that we do the same thing I've done with `Jest`, but with `waitFor` from `testing-library` by adding a new method in the `ITestRunner` interface to implement, like this:

``` ts
export interface ITestRunner {
    spyOn: Function,
    expect: Function,
    resetAllMocks: Function,
    waitingFor: Function
}

    public static TestRunner: ITestRunner = {
        spyOn: typeof jest !== 'undefined' ? jest.spyOn : () => { },
        expect: typeof jest !== 'undefined' ?  expect : () => { },
        resetAllMocks: typeof jest !== 'undefined' ? jest.resetAllMocks : () => { },
        waitingFor: typeof waitFor !== 'undefined' ? waitFor : () => { }
    };
```

That way, we don't have a reference to preact and we can mutualize the code in a single class

What do you think ?

**Comment by alistair-king** [comment]
Thanks for the feedback. All good points. I'll do as you suggest and have something early next week.

**Comment by alistair-king** [comment]
PR updated as per your suggestion. Obviously a much better way to achieve the same thing. Thanks.

**Comment by Mimetis** [comment]
Thanks @alistair-king !!
Now I will ask you if you can include a sample using preact (like we have vite and create-app samples) ?

**Comment by Mimetis** [comment]
up up @alistair-king 
If you do not have the time to integrate a sample; let me know, I will try to make one

**Pull request merged**
